### ISSUE TITLE
Don't use will-change, it's meant to be a troubleshooting property.

### ISSUE THREAD

**Issue by whatsnewsisyphus** [nk-o/visual-portfolio#105]
Will-change with image elements is a memory destroyer, see below, it's not intended for blanket use
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

**Comment by nk-o** [comment]
will-change used for transformations and opacity transitions on elements, so we tell the browser to use GPU instead of CPU and as a result, get smoother animations. I know it is not recommended to use this property on a large number of items on the page, but usually, the portfolio contains a small set of items.
