### ISSUE TITLE
Paginated images doesn't open in external lightboxes

### ISSUE THREAD

**Issue by Kartug01** [nk-o/visual-portfolio#149]
When using "Images" as content source, any kind of pagination, and "URL" as Item click action, only the first images that are loaded are opened in external lightboxes. All images that are loaded via pagination simply navigates to the source image when clicked on.

This seems to occur regardless of what external lightbox you use. The built-in popup lightbox does not have this problem. If you set Items Per Page to "All Items", all images open correctly.

**Comment by nk-o** [comment]
Hey.

How this is related to our plugin? If 3rd-party lightboxes don't support AJAX loaded content, this is no our plugin problem.

**Comment by Kartug01** [comment]
If you've confirmed that it's a 3rd party issue, then fine. However, I've tried using 3 very popular WP lightbox plugins (Simple Lightbox, Responsive Lightbox & Gallery, WP Featherlight), none of which work. I'd assume that the top lightboxes would support AJAX loading.

WP Featherlight specifically mentions supporting AJAX content "by adding data attributes to your content". I've confirmed that only the first loaded images get the correct data-featherlight="image" attribute, while the paginated images do not. Now, I'm too much of a rookie to be able to say who's to blame here, if it's the lightbox plugin that fails to add attributes, or if it's Visual Portfolio that forgets to notify Wordpress or whatever that new content has been added. I'm sure you know best.

A suggestion would be to maybe allow the user to add custom attributes? Like how you allows the user to add a "Rel" attribute?

**Comment by nk-o** [comment]
@Kartug01 some of these plugins support manual initialization methods, that you can use after AJAX loaded by our plugin. I don't see any reason why we should make an integration with plugins, that our plugin does not need. Since we have built-in lightbox features, these plugins are redundant.

If you still want to use these plugins, you will need to manually add scripts. Our jQuery event `endLoadingNewItems.vpf` may help with it https://visualportfolio.co/documentation/developers/jquery-events/

**Comment by Kartug01** [comment]
Thanks for pointing me in the right direction. You were absolutely right, I was able to trigger the lightbox by entering a custom jQuery event in the lightbox plugin. My bad!
