### ISSUE TITLE
Overlapping images on mobile devices on the first load

### ISSUE THREAD

**Issue by nk-o** [nk-o/visual-portfolio#55]
Related topic: https://wordpress.org/support/topic/issues-on-mobile-7/
Related topic: https://wordpress.org/support/topic/problem-with-responsiveness-on-ios-devices/

**Comment by will-ashworth** [comment]
Personally, I noticed this in Safari while using masonry + gallery. My assessment is that the images themselves aren’t being fully loaded before the masonry starts. They need to be, since the browser doesn't know the sizes yet in order to draw a correct grid.

```
removed imagesloaded dependelcy
1.6.3
```

This may solve it. Also, it’s only on first load. Subsequent refreshes work fine.

**Comment by nk-o** [comment]
I thought about it, but we changed images to base64 placeholders, so the browser immediately loads these images and Isotope should work without imagesloaded script. And for me it is working fine. If you could provide an online example, where I can see this bug, I definitely move back imagesloaded script to the plugin code.

**Comment by nk-o** [comment]
Need to test it in coming 1.9.2 update. Imagesloaded moved back.
